name: kids_sbi_env
dependencies:
  - python=3.9
  - future
  - pyyaml
  - numpy
  - scipy
  - astropy
  - pip>=20.0
  - pip:
    - emcee
    - mpi4py
    - healpy
    - interpcl
    - pyDOE
    - numba
